version: '3.9'

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8000:8000'
  #   networks:
  #     - dokploy-network
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.http.routers.backend.rule=Host(`your-domain.com`)' # Change your-domain.com to actual domain
  #     - 'traefik.http.routers.backend.entrypoints=websecure'
  #     - 'traefik.http.routers.backend.tls.certResolver=letsencrypt'
  #     - 'traefik.http.services.backend.loadbalancer.server.port=8000'

  frontend:
    build:
      context: ./mini-app
      dockerfile: Dockerfile
    ports:
      - '6969:6969'
    networks:
      - dokploy-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`your-domain.com`)' # Change your-domain.com to actual domain
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certResolver=letsencrypt'
      - 'traefik.http.services.frontend.loadbalancer.server.port=6969'

networks:
  dokploy-network:
    external: true
