version: '3.9'

services:
  backend:
    image: python:3.12-slim
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./mini-app:/app
    command: ["npm", "run", "dev"]
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=development